# Suppression des conflits sur le port 80
sudo rm -f /etc/nginx/sites-enabled/default
sudo rm -f /etc/nginx/sites-enabled/test-nginx.conf
sudo rm -f /etc/nginx/sites-enabled/handler-nginx.conf

# Écriture de la configuration applicative avec protection FastCGI
sudo tee /etc/nginx/sites-available/monapp.conf > /dev/null << 'EOF'
server {
    listen 80;
    server_name monapp.example.com;
    root /vagrant/http/;
    index index.html;

    # --- Bloc d'authentification (doit être présent) ---
    location = /lmauth {
        internal;
        include /etc/nginx/fastcgi_params;
        fastcgi_pass unix:/var/run/llng-fastcgi-server/llng-fastcgi.sock;
        fastcgi_pass_request_body off;
        fastcgi_param CONTENT_LENGTH "";
        fastcgi_param VHOST $http_host;
        fastcgi_param X_ORIGINAL_URI $request_uri;
    }

    # --- Bloc de l'application ---
    location / {
        auth_request /lmauth;
        auth_request_set $lmremote_user $upstream_http_lm_remote_user;

        # En cas d'erreur 401, on redirige vers le portail
        error_page 401 = http://auth.example.com/?url=$scheme://$http_host$request_uri;

        try_files $uri $uri/ =404;
    }
}
EOF

# Activation du site
sudo ln -sf /etc/nginx/sites-available/monapp.conf /etc/nginx/sites-enabled/

# Configuration globale SSO
sudo /usr/share/lemonldap-ng/bin/lemonldap-ng-cli set domain example.com
sudo /usr/share/lemonldap-ng/bin/lemonldap-ng-cli set cookieName lemonldap

# Initialisation du Virtual Host via ses en-têtes HTTP de sortie
sudo /usr/share/lemonldap-ng/bin/lemonldap-ng-cli addKey exportedHeaders/monapp.example.com Auth-User '$uid'

# Création et configuration de la règle de sécurité par défaut (Restriction UID)
sudo /usr/share/lemonldap-ng/bin/lemonldap-ng-cli addKey locationRules/monapp.example.com default '$uid eq "dwho" or $uid eq "rtyler"'

sudo rm -rf /var/cache/lemonldap-ng/*
sudo systemctl restart llng-fastcgi-server
sudo systemctl restart nginx


# --- client-admin ---
 # dns
 sudo tee -a /etc/hosts > /dev/null << 'EOF'
172.28.128.221 auth.example.com
172.28.128.221 monapp.example.com
EOF

 # 1. Obtenir le nouveau jeton
TOKEN=$(curl -s -c /tmp/cookies.txt "http://auth.example.com/?url=aHR0cDovL21vbmFwcC5leGFtcGxlLmNvbS8=" | grep -oP 'id="token" name="token" value="\K[^"]+')

# 2. Authentification (Login dwho)
curl -s -b /tmp/cookies.txt -c /tmp/cookies.txt -X POST "http://auth.example.com/?url=aHR0cDovL21vbmFwcC5leGFtcGxlLmNvbS8=" \
  -d "user=dwho&password=dwho&token=$TOKEN" > /dev/null

# 3. Accès final à monapp (on espère un 200 OK !)
curl -i -b /tmp/cookies.txt http://monapp.example.com/