# --- Configuration du format et du fichier de sortie ---
# le rapport dans un fichier texte lisible 
sudo tee /etc/logwatch/conf/logwatch.conf <<'EOF'
Output = file
Filename = /var/log/logwatch_rapport.txt
# Filename = /vagrant/logwatch_rapport.txt
Format = text
Detail = Med
Range = Yesterday
EOF

# --- Exécution manuelle du rapport ciblé ---
# Pour générer instantanément le rapport sur l'activité du jour en ciblant uniquement mes services de sécurité et d'infrastructure 
#(sshd, sudo, fail2ban, iptables, et le service web global http), lancez
sudo logwatch --range Today --service http --service fail2ban --service iptables --service sshd --service sudo

# --- Lecture du rapport de sécurité généré ---
sudo cat /var/log/logwatch_rapport.txt

