sudo nano /etc/hosts
172.28.128.221 auth.example.com
172.28.128.221 monapp.example.com
# Vérifiez que le nom pointe bien sur l'IP du serveur
ping -c 3 auth.example.com
ping -c 3 monapp.example.com


# 1. Nettoyage des anciens cookies
rm -f /tmp/cookies.txt

# 2. Récupérer le jeton de connexion sur le portail
TOKEN=$(curl -s -c /tmp/cookies.txt "http://auth.example.com/?url=aHR0cDovL21vbmFwcC5leGFtcGxlLmNvbS8=" | grep -oP 'id="token" name="token" value="\K[^"]+')

# 3. Envoyer les identifiants (Login dwho)
curl -s -b /tmp/cookies.txt -c /tmp/cookies.txt -X POST "http://auth.example.com/?url=aHR0cDovL21vbmFwcC5leGFtcGxlLmNvbS8=" \
  -d "user=dwho&password=dwho&token=$TOKEN" > /dev/null

# 4. Accéder enfin à l'application protégée
curl -i -b /tmp/cookies.txt http://monapp.example.com/